### ISSUE TITLE
Adding Firefox support

### ISSUE THREAD

**Issue by fabiodrg** [aquelemiguel/yt-restore-dislikes#1]
Hey :wave: Great extension! :tada: At the moment it seems I am not part of the experiment (i.e. I still see the dislikes counter), but if Youtube rollouts the changes to everyone I am definitely going use this! 

I use Firefox, so I wonder if you want to accept a few contributions to support both chromium-based and Firefox browsers? :smile: 

Supporting multiple browsers is still tricky in 2021. Starting with the manifest version... You opted for v3, and I think its a good choice because v2 is somewhat deprecated. The problem is that Firefox is still implementing it (and from what I have read there will be some divergence because Mozilla does not agree with Google in some aspects, but that should not be a worry for this particular extension).

Anyway, in order to support Firefox, the following changes are necessary (I did a quick experiment, and tried in chromium and firefox):
- In the manifest.json, set version to 2. Background scripts are necessary, so the `service.js` would be used as such rather than a service worker like in v3.
- In `service.js`, the scripting API is not available for v2. Therefore it would be necessary to override `executeScript` function to use `chrome.tabs.executeScript`.

I would like to ask what do you think is the best approach? I think `service.js` can be common to both browsers. Maybe there is a way to check at runtime `if firefox then callV2Api else callV3Api`. So the main difference is in the manifests files. Maybe have a `manifest_firefox.json` and `manifest_chromium.json`? Note that I think both Chromium and Firefox expect a `manifest.json`. Besides, at least in Firefox, to load an extension permanently I think it needs to be packaged (basically zipping everything). Its one or two additional steps for manual installation.

If you plan to make it easier to install or even distribute it ( API key could be asked via UI ), I can also help on that :wink:

**Comment by aquelemiguel** [comment]
Hey, @fabiodrg! 🤗

Maybe I'll start by informing you that a few days ago, YouTube unfortunately issued [a statement](https://support.google.com/youtube/thread/134791097/update-to-youtube-dislike-counts?hl=en) saying they'll remove the dislike info from their API in about a month. Still, I'd like to make this project the best version of itself until it inevitably gets archived, meaning still going forward with Firefox support.

Onto the issue then. I already had this issue implemented locally with exactly the changes you've suggested, so I think we're on the same page here! I believe it might not be possible to load a specific manifest based on the browser (because as you said, a `manifest.json` file is required by both), so I just went with the easier, uglier approach of copying the code into a `/firefox` folder, downgrading the manifest to V2 and updating `service.js`. I'll submit a pull request later today and tag this issue so you can have a look if you want. 🙂

Regarding the UI, while that's what I meant by the "I might simplify this process in the future" comment on the README, it's likely overkill now that the project is on its deathbed. 😅 But I'm still very thankful for your availability and the insights you wrote here.

**Comment by fabiodrg** [comment]
> it's likely overkill now that the project is on its deathbed

Yup, that's true, I wasn't aware that Youtube would drop the dislikes count from the API.. oh well, thanks for the Firefox love :wink:
